repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.45.0  # Use the revision or tag you want
    hooks:
      - id: ruff
        args: ['--fix']
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1  # Use the revision or tag you want
    hooks:
      - id: mypy